### ISSUE TITLE
Als admin wil ik spellen kunnen toevoegen, verwijderen of aanpassen aan de app

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#10]
**Omschrijving:**
De ALO studenten willen de spellen kunnen beheren. Er zullen nieuwe spellen worden ontwikkeld, die toegevoegd moeten worden. Oudere spellen moeten of aangepast of verwijderd worden.

**Tasks:**
- [ ] - Wireflows maken voor het beheren van de spellen
- [ ] - Overzichts paginas/componenten aanpassen op basis van de wireflows
- [ ] - Pagina maken voor het toevoegen van nieuw spel
- [ ] - Edit pagina maken voor het bewerken van bestaande spel

**Definition of Done:**
De admin kan op de overzichtpagina een spel verwijderen of bewerken door icoontjes. Een knop om nieuwe spellen toe te voegen lijdt naar een nieuwe pagina die deze spellen toevoegt. 

**Notes**
De backend taken hiervoor komen in de repo voor de API te staan (https://github.com/iSirThijs/jungle-gym-api/issues)

**Comment by iamDistractech** [comment]
Deze is klaar, want we hebben een keuze gemaakt om nu strapi te gebruiken. Toekomstig kan het nog verwerkt worden in de app

**Comment by iamDistractech** [comment]
> Deze is klaar, want we hebben een keuze gemaakt om nu strapi te gebruiken. Toekomstig kan het nog verwerkt worden in de app
