### ISSUE TITLE
Als gebruiker wil ik spellen kunnen vinden met een filterfunctie

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#2]
**Omschrijving:**
In het overzicht moet gefilterd kunnen worden met leerlijnen, groepen en materiaal.

Beschikbare filters zijn:
- **Leerlijnen** (balanceren, mikken, hardlopen, springen, doelspelen, tikspelen, stoeispelen, bewegen op muziek & jongleren)
- **Groepen** (groep 1 & 2, groep 3 & 4, groep 5 & 6, groep 7 & 8)
- **Materialen** (lijst met materialen zodat ze kunnen aanvinken wat er beschikbaar is; ballen, hoedjes, touwen, slaghout, frisbee, etc).
- **Leerlingenaantal**

**Tasks:**
- [x] Onderzoek doen naar verschillende soorten filters die worden gebruikt
- [x] Wireflow voor filteren uitbreiden naar meerdere opties  [Figma design](https://www.figma.com/file/3JDybgdoSvAo1UTacZt8ML/JungleGym_concept?node-id=0%3A1)
- [x] #31 
- [x] #34
- [x] Elke filter optie creeren
- [ ] Functionaliteiten van filter werkend krijgen

**Definition of Done:**
Op het moment dat het overzicht veranderd op basis van de filter die de gebruiker gebruikt.

**Comment by iamDistractech** [comment]
#94 closed this issue
