### ISSUE TITLE
Als gebruiker wil ik kunnen zien wat een spel inhoudt; wat de regels zijn en welke materialen ik nodig heb

### ISSUE THREAD

**Issue by jochemvogel** [iSirThijs/jungle-gym#4]
**Omschrijving:**
Een detailpagina voor een spel met alle benodigde informatie

**Tasks:**
- [x] https://github.com/iSirThijs/jungle-gym/issues/13
- [x] https://github.com/iSirThijs/jungle-gym/issues/28
- [x] https://github.com/iSirThijs/jungle-gym/issues/30
- [x] https://github.com/iSirThijs/jungle-gym/issues/33

**Definition of Done:**
Op het moment dat er een (statische) detailpagina is voor een van de spellen

**Comment by jochemvogel** [comment]
User story is afgerond.
